In [2]:
import torch
import torchvision
import torch.nn as nn
import numpy as np

In [3]:
arr = [[1], [2], [3]]
print(arr)

[[1], [2], [3]]


In [4]:
numpy = np.array(arr)
print(numpy)

[[1]
 [2]
 [3]]


In [5]:
# 2 cách chuyển đổi numpy sang torch, và vì thao tác trong deeplearning là số thực nên thường là floattensor
t = torch.FloatTensor(arr)
t2 = torch.tensor(arr, dtype=torch.float32)
print(f'Tensor 1:{t}, \n Tensor 2: {t2}')

Tensor 1:tensor([[1.],
        [2.],
        [3.]]), 
 Tensor 2: tensor([[1.],
        [2.],
        [3.]])


# Khởi tạo tensor

In [6]:
y = torch.rand(4, 5)
print('Our Tensor 2D:\n', y)
print('Dimension:', y.ndim)
print('Shape:', y.shape)

Our Tensor 2D:
 tensor([[0.9713, 0.7400, 0.5126, 0.3588, 0.6448],
        [0.8369, 0.7942, 0.6082, 0.2929, 0.2694],
        [0.2450, 0.2031, 0.2852, 0.2338, 0.8136],
        [0.9939, 0.3972, 0.9187, 0.8338, 0.7957]])
Dimension: 2
Shape: torch.Size([4, 5])


# Các phép tính

In [7]:
tensor_1 = torch.rand(3,3,3)
tensor_2 = torch.rand(3,3,3)
print('Phep cong:', tensor_1+tensor_2)
# Không có phép nhân cho 2 khối tensor 3D,
#nên bmm hoạt động giống việc tách ra 3 ma trận 3x3 và nhân lần lượt gọi là batch matrix multiply
print('Phep nhan:', torch.bmm(tensor_1, tensor_2))

Phep cong: tensor([[[1.0211, 0.5710, 1.4790],
         [0.9734, 1.0870, 1.3190],
         [1.5968, 0.7321, 0.3107]],

        [[1.1418, 1.3967, 0.9824],
         [0.7980, 1.3856, 1.3911],
         [1.4280, 0.7629, 0.5565]],

        [[1.0652, 0.9052, 0.6892],
         [1.3976, 1.2514, 1.5134],
         [0.6980, 0.7257, 1.1300]]])
Phep nhan: tensor([[[0.8612, 0.7088, 0.5896],
         [1.0729, 0.8767, 0.8183],
         [0.5600, 0.6765, 0.7382]],

        [[1.2533, 1.2223, 1.4279],
         [0.9530, 0.7747, 0.6364],
         [0.5524, 0.7959, 0.6529]],

        [[0.5785, 0.7783, 0.6702],
         [1.0515, 1.2326, 1.0529],
         [0.6060, 0.6050, 0.4966]]])


In [8]:
tensor_3 = torch.rand(2,4)
# Cú pháp .transpose(input, dimension0, dimension1) # vị trí 2 dimension mà bạn muốn swap
tensor_4 = torch.transpose(tensor_3, 0, 1)
print('Truoc khi transpose:', tensor_3)
print('Sau khi transpose', tensor_4)

Truoc khi transpose: tensor([[0.2029, 0.8258, 0.2862, 0.2750],
        [0.6932, 0.0901, 0.6932, 0.4843]])
Sau khi transpose tensor([[0.2029, 0.6932],
        [0.8258, 0.0901],
        [0.2862, 0.6932],
        [0.2750, 0.4843]])


# Indexing

In [10]:
tensor_5 = torch.rand(4, 3)
print('Our tensor\n', tensor_5)
print(tensor_5[0])
print(tensor_5[-1])
print(tensor_5[:-1, : 2]) #Giống slicing bên numpy

Our tensor
 tensor([[0.1468, 0.4805, 0.1910],
        [0.0321, 0.0923, 0.4401],
        [0.8460, 0.8222, 0.6301],
        [0.0071, 0.5263, 0.6716]])
tensor([0.1468, 0.4805, 0.1910])
tensor([0.0071, 0.5263, 0.6716])
tensor([[0.1468, 0.4805],
        [0.0321, 0.0923],
        [0.8460, 0.8222]])


# Describing tensor

In [12]:
tensor_6 = torch.rand(3, 2)
print('Shape:', tensor_6.shape)
print('Datatype:', tensor_6.dtype)
print('Number of dimensions:', tensor_6.ndim)
print('Number of elements:', tensor_6.numel())

Shape: torch.Size([3, 2])
Datatype: torch.float32
Number of dimensions: 2
Number of elements: 6


# Reshape

In [20]:
tensor_7 = torch.rand(2,3,4)
print(tensor_7)
print(tensor_7.reshape(6,4))
print(tensor_7.reshape(2, -1))
print('Tensor 1D flatten:\n', tensor_7.flatten())

tensor([[[0.4229, 0.5706, 0.9288, 0.0807],
         [0.9765, 0.4200, 0.9117, 0.2460],
         [0.2610, 0.6467, 0.1408, 0.3791]],

        [[0.0084, 0.7872, 0.7098, 0.9221],
         [0.3810, 0.9335, 0.8681, 0.5024],
         [0.0097, 0.7614, 0.8839, 0.8755]]])
tensor([[0.4229, 0.5706, 0.9288, 0.0807],
        [0.9765, 0.4200, 0.9117, 0.2460],
        [0.2610, 0.6467, 0.1408, 0.3791],
        [0.0084, 0.7872, 0.7098, 0.9221],
        [0.3810, 0.9335, 0.8681, 0.5024],
        [0.0097, 0.7614, 0.8839, 0.8755]])
tensor([[0.4229, 0.5706, 0.9288, 0.0807, 0.9765, 0.4200, 0.9117, 0.2460, 0.2610,
         0.6467, 0.1408, 0.3791],
        [0.0084, 0.7872, 0.7098, 0.9221, 0.3810, 0.9335, 0.8681, 0.5024, 0.0097,
         0.7614, 0.8839, 0.8755]])
Tensor 1D flatten:
 tensor([0.4229, 0.5706, 0.9288, 0.0807, 0.9765, 0.4200, 0.9117, 0.2460, 0.2610,
        0.6467, 0.1408, 0.3791, 0.0084, 0.7872, 0.7098, 0.9221, 0.3810, 0.9335,
        0.8681, 0.5024, 0.0097, 0.7614, 0.8839, 0.8755])


# Unsqueeze và squeeze

In [22]:
tensor_8 = torch.rand(2,3)
#Unsqueeze nhằm thêm một dimension mới có size là 1 vào index dimension chỉ định
# Ví dụ khởi tạo shape ban đầu là (2,3) unsqueeze ở vị trí 0 -> shape mới: (1,2,3)
tensor_9 = tensor_8.unsqueeze(0)
tensor_10 = tensor_8.unsqueeze(2)
print('Shape initially:', tensor_8.shape)
print('Shape afterwards:', tensor_9.shape)
print('Shape afterwards:', tensor_10.shape)

Shape initially: torch.Size([2, 3])
Shape afterwards: torch.Size([1, 2, 3])
Shape afterwards: torch.Size([2, 3, 1])


In [25]:
# Squeeze sẽ remove những chiều có kích thước là 1
tensor_a = torch.rand(3,1,2,1)
print('Shape initially:', tensor_a.shape)
print('Shape afterwards:', tensor_a.squeeze(1).shape)
print('Shape afterwards:', tensor_a.squeeze().shape) #Remove tất cả dimension có size=1

Shape initially: torch.Size([3, 1, 2, 1])
Shape afterwards: torch.Size([3, 2, 1])
Shape afterwards: torch.Size([3, 2])


# Broadcast

In [28]:
#Broadcast là phép giúp cho 2 tensor có cùng kích thước để thực hiện phép tính
# Quy ước: nếu có 1 trong 2 tensor có dimension=1-> Lấy dimension còn lại
# Hoặc nếu có dimension bằng nhau trong 2 tensor rồi thì thôi
tensor_b = torch.rand(2,3,1,4)
tensor_c = torch.rand(1,3,3,1)
print('Shape output:', (tensor_b+tensor_c).shape)

Shape output: torch.Size([2, 3, 3, 4])
